config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'home#index'

  resource :admins do
    get :manage_influencer
    get :manage_advertiser
    get :social_accounts
    get :reported_ads
    get :newsletter
    get :ad_review
    get :reported_ad_mail
    get :app_configurations
    post :reset_password
    post :get_notifications
    post :send_mail_from_admin
  end

  resources :advertisements do
    collection do
      post :approve_ads
      post :decline_ads
    end
  end

  resources :news_letters do
    collection do
      post :send_newsletters
    end

  end
  resource :app_configurations
  resources :influencers
  resources :advertisers

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base

  TYPE = { "Link"=>1,"Photo"=> 2, "Video"=>3}
  PLATFORMS = {"Facebook"=>1,"Instagram"=>2, "Both" => 3}
  STATUS =  {"Initiated" => 1,"Approved by Admin" => 2,"Approved by influencer" => 3,"Declined by Admin" => 4, "Declined by influencer"=>5,"Published by influencer"=>6}
  STATUS_TEXT = ["A new Advertisement for You","Advertisement Approved By Admin","Advertisement Approved By Influencer","Advertisement Declined By Admin","Declined By Influencer","Published By Influencer"]

  def self.get_advertisement_count_of_particular_advertiser(advertiser_id)
    count = Advertisement.where(:advertiser_id => advertiser_id).count
    count
  end
 # influencer_id: '1' advertiser_id: '6' category: celebrity advertisement_status: '3' ivars: :@permitted: false
  def self.search(params)
    # raise params.to_yaml
    conditions = []
    conditions << "influencer_id = #{params[:influencer_id]}" if params[:influencer_id].present?
    conditions << "advertiser_id =' #{params[:advertiser_id]}'" if params[:advertiser_id].present?
    conditions << "status = #{params[:advertisement_status]}" if params[:advertisement_status].present?
    condition = conditions.join(' and ')
    self.where(condition)
  end

end

app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
     has_many :advertisements

    scope :most_recent, -> (limit) { order("created_at desc").limit(limit) }

  def self.reset_password
  end

end

app/models/app_configuration.rb
class AppConfiguration < ActiveRecord::Base
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	belongs_to :advertiser
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/influencer.rb
class Influencer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_one :social_account
    has_one :influencer_financial_info

    has_many :advertisements
    scope :most_recent, -> (limit) { order("created_at desc").limit(limit) }
    def online
      if self.last_sign_in_at < 5.minutes.from_now
        true
      else
        false
      end
    end

end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  ACTIVITY_TYPE = {"advertiser_sign_up"=>1,"influencer_sign_up"=>2,"new_ad_creation"=>3,"new_ad_published"=>4}
end

app/models/page_insight.rb
class PageInsight < ActiveRecord::Base
  serialize :page_consumptions_by_consumption_type
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/social_account.rb
class SocialAccount < ActiveRecord::Base
  validates_uniqueness_of :facebook_page_id
  # has_one :page_insight, :foreign_key => :facebook_page_id
  def self.search(params)
    # raise params.to_yaml
    conditions = []
    conditions << "platform_type_id = '#{params[:platform_type_id]}'" if params[:platform_type_id].present?
    conditions << "country = '#{params[:country]}'" if params[:country].present?
    conditions << "category = '#{params[:category]}'" if params[:category].present?
    condition = conditions.join(' and ')
    if params[:facebook_page_count].present? and params[:facebook_page_count] == "htol"
      self.where(condition).order('facebook_page_count DESC')
    elsif params[:facebook_page_count].present? and params[:facebook_page_count] == "ltoh"
      self.where(condition).order('facebook_page_count ASC')
    else
      self.where(condition)
    end

  end

  def page_insight
    PageInsight.where(:facebook_page_id=>self.facebook_page_id)
  end

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
 end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_admin!

  def index
    if !current_admin.has_role? :Admin
      flash[:danger] = "You Are Not the Authentic Admin, Contact Admin to get access"
      reset_session
      redirect_to "/unauthorized"
    else
      @earned_today = today_earning
      @monthly_earning = monthly_earning
      @published_ad_count = published_ad_count
      @infleuncer_count = Influencer.count
      @recent_registered_advertisers = Advertiser.most_recent(5)
      @recent_registered_influencers = Influencer.most_recent(5)
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/helpers/news_letters_helper.rb
module NewsLettersHelper
end

app/views/admins/ad_review.html.erb
<%=render :partial=>"layouts/header"%>
<%=render :partial=>"layouts/left_panel"%>
<section class="main-content-wrapper column">
   <section id="main-content">
        <div class="row">
           <div class="col-md-12">
             <%= render :partial => "layouts/breadcrumb", :locals => {:breadcrumb => @breadcrumb}%>
             <h1 class="h1"><i class="fa fa-pencil-square-o"></i> Ad Review</h1>
            </div>
       </div>
       <div class="row">
       <div class="col-md-12">
       <div class="borderBox">
       <div class="row">
       <%=form_for :search,:url=>ad_review_admins_path, :method=>"get" do |f|%>

       <div class="col-md-3">
       <div class="form-group">
       <label class="" for="">Influencer</label>
       <%=select_tag(:influencer_id,options_for_select(Influencer.all.collect{ |u| ["#{u.name}(#{u.email})",u.id]},params[:search][:influencer_id]),{:prompt=>"Select Influencer",:class=>"form-control",:name=>"search[influencer_id]"})%>
       </div>
       </div>

       <div class="col-md-3">
       <div class="form-group">
       <label class="" for="">Advertiser</label>
       <%=select_tag(:advertiser_id,options_for_select(Advertiser.all.collect{ |u| ["#{u.name}(#{u.email})",u.id]},params[:search][:advertiser_id]),{:prompt=>"Select Advertiser",:class=>"form-control",:name=>"search[advertiser_id]"})%>
       </div>
       </div>

       <div class="col-md-3">
       <div class="form-group">
         <label class="" for="">Category</label>
         <%=f.select(:category,options_for_select(Category.pluck(:category_name),params[:search][:category]),{},:class=>"form-control", :name=>"search[category]")%>
         </div>
       </div>

       <div class="col-md-3">
       <div class="form-group">

       <label class="" for="">Status</label>
       <%=select_tag(:advertisement_status,options_for_select(Advertisement::STATUS,params[:search][:advertisement_status]),{:prompt=>"Ad Status",:class=>"form-control",:name=>"search[advertisement_status]"})%>
          </div>
       </div>

       <div class="col-md-3">
         <button type="submit" class="btn btn-primary">Search</button>
         <a href="/admins/ad_review" class="btn btn-primary">Clear</a>
       </div>

       <%end%>

       </div>

       <!-- <div class="row">
       <div class="col-md-12">
       <div class="pull-left">Search By:</div>
       <div class="btn-toolbar">
       <div class="btn-group btn-group-sm">
       <a href="<%=news_letters_path(alphabet:'a')%>" class="btn btn-default">A</a>
       <a href="<%=news_letters_path(alphabet:'b')%>" class="btn btn-default">B</a>
       <a href="<%=news_letters_path(alphabet:'c')%>" class="btn btn-default">C</a>
       <a href="<%=news_letters_path(alphabet:'d')%>" class="btn btn-default">D</a>
       <a href="<%=news_letters_path(alphabet:'e')%>" class="btn btn-default">E</a>
       <a href="<%=news_letters_path(alphabet:'f')%>" class="btn btn-default">F</a>
       <a href="<%=news_letters_path(alphabet:'g')%>" class="btn btn-default">G</a>
       <a href="<%=news_letters_path(alphabet:'h')%>" class="btn btn-default">H</a>
       <a href="<%=news_letters_path(alphabet:'i')%>" class="btn btn-default">I</a>
       <a href="<%=news_letters_path(alphabet:'j')%>" class="btn btn-default">J</a>
       <a href="<%=news_letters_path(alphabet:'k')%>" class="btn btn-default">K</a>
       <a href="<%=news_letters_path(alphabet:'l')%>" class="btn btn-default">L</a>
       <a href="<%=news_letters_path(alphabet:'m')%>" class="btn btn-default">M</a>
       <a href="<%=news_letters_path(alphabet:'n')%>" class="btn btn-default">N</a>
       <a href="<%=news_letters_path(alphabet:'o')%>" class="btn btn-default">O</a>
       <a href="<%=news_letters_path(alphabet:'p')%>" class="btn btn-default">P</a>
       <a href="<%=news_letters_path(alphabet:'q')%>" class="btn btn-default">Q</a>
       <a href="<%=news_letters_path(alphabet:'r')%>" class="btn btn-default">R</a>
       <a href="<%=news_letters_path(alphabet:'s')%>" class="btn btn-default">S</a>
       <a href="<%=news_letters_path(alphabet:'t')%>" class="btn btn-default">T</a>
       <a href="<%=news_letters_path(alphabet:'u')%>" class="btn btn-default">U</a>
       <a href="<%=news_letters_path(alphabet:'v')%>" class="btn btn-default">V</a>
       <a href="<%=news_letters_path(alphabet:'w')%>" class="btn btn-default">W</a>
       <a href="<%=news_letters_path(alphabet:'x')%>" class="btn btn-default">X</a>
       <a href="<%=news_letters_path(alphabet:'y')%>" class="btn btn-default">Y</a>
       <a href="<%=news_letters_path(alphabet:'z')%>" class="btn btn-default">Z</a>
       </div>
       </div>
       </div>
       </div> -->
       </div>
       </div>
   </div>
     <div class="row">
           <div class="col-md-12">
               <div class="panel panel-default">
                 <div class="panel-heading">
                   <h3 class="panel-title">Ad Review Listing</h3>
                   <div class="actions pull-right">
                       <i class="fa fa-chevron-down"></i>
                   </div>
                 </div>
                 <div class="panel-body">

                   <div class="table-responsive">
                   <table id="example" class="table table-striped table-responsive" cellspacing="0" width="100%">
                   <thead>
                       <tr>
                          <th>ID</th>
                           <th>Ad Preview</th>
                           <!-- <th>Category</th> -->
                           <th>Advertiser Name</th>
                           <th>Advertiser Email</th>
                           <th>Influencer Name</th>
                           <th>Influencer Email</th>
                           <th>Current Status</th>
                           <!-- <th>Reason for decline</th> -->
                           <th>Action</th>
                       </tr>
                   </thead>

                   <tbody>
                     <%@advertisements.each do |advertisement|%>
                       <tr>
                         <td><%=advertisement.id%></td>
                           <td>
                             <%if advertisement.ad_image_url.present?%>
                             <img src="<%=advertisement.ad_image_url%>" alt="Ad Preview" class="img-thumb"></td>
                             <%else%>
                             <img src="http://res.cloudinary.com/dhdl31ov5/image/upload/v1485755708/ad-na_voqzga.png" alt="Ad Preview" class="img-thumb"></td>
                             <%end%>
                           <td><%= Advertiser.find(advertisement.advertiser_id).name  rescue nil%></td>
                           <td><%= Advertiser.find(advertisement.advertiser_id).email  rescue nil%></td>
                           <td><%= Influencer.find(advertisement.influencer_id).name rescue nil %></td>
                           <td><%= Influencer.find(advertisement.influencer_id).email rescue nil %></td>
                           <td><%= Advertisement::STATUS.key (advertisement.status )%> </td>
                           <!-- <td><%#=advertisement.reason_for_decline%> </td> -->
                           <td>
                             <%if advertisement.status == Advertisement::STATUS["Published by influencer"] %>
                              <p>Published</p>
                                <%elsif advertisement.status == Advertisement::STATUS["Declined by influencer"]%>
                              <p>Declined by influencer</p>
                                <%elsif advertisement.status == approved_by_admin%>
                              <p>Approved by you(Admin)</p>
                              <%elsif advertisement.status == Advertisement::STATUS["Declined by Admin"]%>
                              <p>Declined by you(Admin)</p>
                             <%else%>
                             <a href=" <%=approve_ads_advertisements_path(id:advertisement.id)%>" data-method="post" class="btn btn-success btn-xs">Approve</a>
                             <a href=" <%=decline_ads_advertisements_path(id:advertisement.id)%>" data-method="post" class="btn btn-danger btn-xs" onclick="show_decline_modal(<%=advertisement.id%>)">Decline</a>
                             <%end%>
                           </td>
                       </tr>
                       <%end%>
                   </tbody>
               </table>
               </div>
               <%=will_paginate @advertisements, renderer: BootstrapPagination::Rails%>
                </div>
            </div>
       </div>
   </div>
   <!-- <div class="modal fade" id="declinePopup">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Ad Decline</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12">
          <%=form_tag "#",:class=>"form" do |f|%>
            <%=hidden_field_tag(:declined_ad_id,"")%>
            <%=text_area_tag(:reason_for_ad_decline,"",:placeholder=>"Enter Reason for declining the ad ",:class=>"form-control",:required=>true)%>
            <%=submit_tag("Submit", :class=>"btn btn-mountain btn-sm btn-round",:onclick=>"decline_ad_by_influencer()")%>
          <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> -->

<script>
  function show_decline_modal(id){
    event.preventDefault();
    $("#declined_ad_id").val(id);
    $("#declinePopup").modal("show");
  }
</script>
 </section>
</section>

app/views/admins/manage_advertiser.html.erb
<%=render :partial=>"layouts/header"%>
<%=render :partial=>"layouts/left_panel"%>
<section class="main-content-wrapper column">
    <section id="main-content">
         <div class="row">
            <div class="col-md-12">
                <%= render :partial => "layouts/breadcrumb", :locals => {:breadcrumb => @breadcrumb}%>
            </div>
        </div>

      <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Manage Advertiser List</h3>
                    <div class="actions pull-right">
                        <i class="fa fa-chevron-down"></i>
                    </div>
                  </div>
                  <div class="panel-body">
                    <div class="table-responsive">

                    <table id="example" class="table table-striped" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Total Advertisements created</th>
                            <th>Email</th>
                             <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                      <%@advertisers.each do |advertiser|%>
                        <tr id="row_<%=advertiser.id%>">
                            <td><%=advertiser.name%></td>
                            <td><%=Advertisement.get_advertisement_count_of_particular_advertiser(advertiser.id) %></td>
                            <td><%=advertiser.email %></td>
                             <td>
                              <a onclick="delete_advertiser(<%=advertiser.id%>)" href="#" class="red"><i class="fa fa-trash" title="Delete"></i></a>
                              <!-- <a href="<%#=reset_password_admins_path(type:'advertiser',id:advertiser.id)%>" data-method="post" data-remote="true"
                                onclick="show_success_message('password_reset')" class="green"><i class="fa fa-refresh" title="reset password"></i></a> -->
                            </td>
                        </tr>
                        <%end%>
                    </tbody>
                </table>
              </div>
                <%=will_paginate @advertisers%>
               </div>
             </div>
        </div>
    </div>

    </section>
 </section>
 <script>
 function delete_advertiser(advertiser_id){
   event.preventDefault();
   $.ajax({
     url:  "/advertisers/"+advertiser_id,
     type: "DELETE",
     success: function (response){
       if(response["success"] == true){
         toastr.success("Successfully Deleted");
         $("#row_"+advertiser_id).hide(500);
       }
     }
   })
 }
 </script>

app/views/admins/manage_influencer.html.erb
<%=render :partial=>"layouts/header"%>
<%=render :partial=>"layouts/left_panel"%>
<section class="main-content-wrapper column">
    <section id="main-content">
         <div class="row">
            <div class="col-md-12">
                <%= render :partial => "layouts/breadcrumb", :locals => {:breadcrumb => @breadcrumb}%>
            </div>
        </div>

      <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Manage Influencers List</h3>
                    <div class="actions pull-right">
                        <i class="fa fa-chevron-down"></i>
                    </div>
                  </div>
                  <div class="panel-body">
                      <div class="table-responsive">
                    <table id="example" class="table table-striped" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>facebook_page_count</th>
                            <th>facebook_page_id</th>
                            <th>Publishing Price</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                      <%@influencers.each do |influencer|%>
                        <tr id="row_<%=influencer.id%>">
                            <td><a href="<%=influencers_path(id:influencer.id)%>"><%=influencer.name%></a></td>
                            <td><%=influencer.email%></td>
                            <td><%=influencer.social_account.facebook_page_count rescue nil%></td>
                            <td><%=influencer.social_account.platform_type_id rescue nil%></td>
                            <td><%=influencer.publishing_price.present? ? "$ "+influencer.publishing_price : "Not provided" %></td>
                            <td>
                              <!-- <a href="#" class="green"><i class="fa fa-edit" title="Edit"></i></a> -->
                              <a href="#" onclick="delete_influencer(<%=influencer.id%>)" class="red"><i class="fa fa-trash" title="Delete"></i></a>
                              <a href="javascript:void(0)" onclick="show_mail_modal('<%=influencer.email%>')" class="blue"><i class="fa fa-envelope" title="Mail"></i></a>
                            </td>
                        </tr>
                        <%end%>
                    </tbody>
                </table>
              </div>
              <script>
              function show_mail_modal(email){
                $("#myModal").modal("show");
                $("#mailing_email").val(email);
              }
              </script>

              <div id="myModal" class="modal"  >
                   <div class="modal-dialog">

                     <!-- Modal content-->
                     <div class="modal-content">
                       <div class="modal-header">
                         <button type="button" class="close" data-dismiss="modal">&times;</button>
                         <h4 class="modal-title">Mailer</h4>
                       </div>
                       <div class="modal-body">
                        <%=form_for "mail",:url=>  send_mail_from_admin_admins_path,:method=>"post" do %>
                        <div class="form-group">
                          <%=text_field_tag :mailing_email,"",:placeholder=>"Email",:class=>"form-control"%>
                        </div>
                        <div class="form-group">
                          <%=text_field_tag :subject,"",:placeholder=>"Subject",:class=>"form-control"%>
                        </div>
                        <div class="form-group">
                          <%=text_area_tag :message,"",:placeholder=>"Enter",:class=>"form-control"%>
                        </div>
                        <div class="form-group">
                          <%=submit_tag "Send",:class=>"btn btn-success"%>
                        </div>
                          <%end%>
                       </div>
                       <div class="modal-footer">
                         <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                       </div>
                     </div>
                   </div>
                 </div>

                <%=will_paginate @influencers%>
                <%= page_entries_info @influencers%>
               </div>
             </div>
        </div>
    </div>

    </section>
 </section>
<script>
function delete_influencer(influencer_id){
  event.preventDefault();
  var check = window.confirm("Are you sure?","Yes","No");
  if (check){
    $.ajax({
      url:  "/influencers/"+influencer_id,
      type: "DELETE",
      success: function (response){
        if(response["success"] == true){
          toastr.success("Successfully Deleted");
          $("#row_"+influencer_id).hide(500);
        }
      }
    })
  }
}
</script>

app/views/layouts/_breadcrumb.html.erb
<ol class="breadcrumb">
  <% breadcrumb.each do |key, val| %>
  	<% if val.present? %>
      <li><a href="<%= val %>"><%= key %></a></li>
    <% else %>
    	<li  class="active"><strong><%= key %></strong></li>
    <% end %>
  <% end %>
</ol>

app/views/layouts/_header.html.erb
        <header id="header">
            <!--logo start-->
            <div class="brand">
                <a href="<%=root_url%>" class="logo"><span>Social</span>Booker</a>
            </div>
            <!--logo end-->
            <div class="toggle-navigation toggle-left">
                <button type="button" class="btn btn-default" id="toggle-left" data-toggle="tooltip" data-placement="right" title="Toggle Navigation">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <script>
              $('#toggle-left').bind('click',function() {
                $(".sidebar").toggleClass("sidebar-toggle");
                $(".main-content-wrapper").toggleClass("main-content-toggle-left");
              });
            </script>
            <div class="user-nav">
                <ul >
                    <li class="dropdown messages hidden">
                        <span class="badge badge-danager animated bounceIn" id="new-messages">38</span>
                        <button type="button" class="btn btn-default dropdown-toggle options" id="toggle-mail"  data-toggle="dropdown">
                           <!-- onclick="show_messages_dropdown()" -->
                          <!--  -->
                            <i class="fa fa-envelope"></i>
                        </button>
                        <ul class="dropdown-menu alert animated fadeInDown" id="messages-dropdown">
                            <li>
                                <h1>You have <strong>38</strong> new messages</h1>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="profile-photo">
                                        <!-- <img src="/assets/img/avatar.gif" alt="" class="img-circle"> -->
                                    </div>
                                    <div class="message-info">
                                        <span class="sender">James Bond</span>
                                        <span class="time">30 mins</span>
                                        <div class="message-content">Lorem ipsum dolor sit amet, elit rutrum felis sed erat augue fusce...</div>
                                    </div>
                                </a>
                            </li>

                            <li><a href="#">Check all messages <i class="fa fa-angle-right"></i></a>
                            </li>
                        </ul>

                    </li>
                    <li class="profile-photo">
                        <img src="/assets/member-img.png" alt="" class="img-circle">
                    </li>
                    <li class="dropdown settings">
                        <a class="dropdown-toggle"  data-toggle="dropdown" href="#">
                          <!-- id="user_name_link" onclick="show_user_dropdown()" -->
                      <%=current_admin.name%> <i class="fa fa-angle-down"></i>
                    </a>
                        <ul class="dropdown-menu animated fadeInDown" id="admin-dropdown">
                            <!-- <li>
                                <a href="#"><i class="fa fa-user"></i> Account</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-calendar"></i> Settings</a>
                            </li> -->
                            <li>
                                <a href="<%=destroy_admin_session_path%>" data-method="delete"><i class="fa fa-power-off"></i> Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </header>

<script>
// setInterval(get_notification, 1000);
function get_notification(){
  $.ajax({
    url:"/admins/get_notifications",
    type:"POST",
    data:{
      count_only:true
    },
    success: function(response){
      //  $("#notification-dropdown").append("<li><a href=''><div class='message-info'><div class='message-content'>"+response["notifications"][0][1]+"</div></li>");
      console.log(response);
    }
  });
}

function show_user_dropdown(){
  if ($('#messages-dropdown').is(":visible") == true) {
       $('#messages-dropdown').toggle();
       $('#admin-dropdown').toggle();
  }
  else {
      $('#admin-dropdown').toggle();
    }
  }

function show_messages_dropdown(){
  if ($('#admin-dropdown').is(":visible") == true) {
      $('#admin-dropdown').toggle();
      $('#messages-dropdown').toggle();
  }
  else {
     $('#messages-dropdown').toggle();
   }
  }
  // $(document.body).on("click",function(){
  //   if($('#admin-dropdown').is(":visible") == true){
  //     $('#admin-dropdown').hide();
  //     console.log("asd")
  //     }
  //     if(  $('#messages-dropdown').is(":visible") == true) {
  //       $('#messages-dropdown').hide();
  //       console.log("asd")
  //     }
  // });

</script>

app/views/layouts/_left_panel.html.erb
<aside class="sidebar column">
    <div id="leftside-navigation" class="nano">
        <ul class="nano-content">
            <li class="active">
                <a href="<%=root_path%>"><i class="fa fa-dashboard"></i><span>Dashboard</span></a>
            </li>
            <li>
                <a href="<%=manage_influencer_admins_path%>"><i class="fa fa-user"></i><span>Manage Influencer</span></a>
            </li>
            <li>
                <a href="<%=manage_advertiser_admins_path%>"><i class="fa fa-user"></i><span>Manage Advertiser</span></a>
            </li>
            <!-- <li>
                <a href="<%#=social_accounts_admins_path%>"><i class="fa fa-users"></i><span>Social Accounts</span></a>
            </li> -->
            <li>
                <a href="<%=ad_review_admins_path%>"><i class="fa fa-pencil-square-o"></i><span>Ad Review</span></a>
            </li>
            <li>
                <a href="<%=reported_ads_admins_path%>"><i class="fa fa-bar-chart"></i><span>Reported Ad</span></a>
            </li>
            <li>
                <a href="<%=app_configurations_admins_path%>"><i class="fa fa-cog"></i><span>APP Configurations</span></a>
            </li>
            <li>
                <a href="<%=news_letters_path%>"><i class="fa fa-bullhorn"></i><span>Newsletter</span></a>
            </li>
            <!-- <li>
                <a href=" "><i class="fa fa-usd"></i><span>Change Fees</span></a>
            </li>
            <li>
                <a href=""><i class="fa fa-cogs"></i><span>Social Accounts Integration</span></a>
            </li> -->
        </ul>
    </div>
</aside>

app/views/layouts/application.html.erb
<html>
<head>
  <title>SbAdmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
   </head>

<body class="animated fadeIn">
  <% unless flash.empty? %>
 <script type="text/javascript">
     <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
     <% end %>
 </script>
 <% end %>
  <section id="container">
    <div id="equalheight">
      <%= yield %>
    </div>
  </section>
</body>
</html>