config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'home#index'

  resource :admins do
    get :manage_influencer
    get :manage_advertiser
    get :social_accounts
    get :reported_ads
    get :newsletter
    get :ad_review
    get :reported_ad_mail
    get :app_configurations
    post :reset_password
    post :get_notifications
    post :send_mail_from_admin
  end

  resources :advertisements do
    collection do
      post :approve_ads
      post :decline_ads
    end
  end

  resources :news_letters do
    collection do
      post :send_newsletters
    end

  end
  resource :app_configurations
  resources :influencers
  resources :advertisers

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base

  TYPE = { "Link"=>1,"Photo"=> 2, "Video"=>3}
  PLATFORMS = {"Facebook"=>1,"Instagram"=>2, "Both" => 3}
  STATUS =  {"Initiated" => 1,"Approved by Admin" => 2,"Approved by influencer" => 3,"Declined by Admin" => 4, "Declined by influencer"=>5,"Published by influencer"=>6}
  STATUS_TEXT = ["A new Advertisement for You","Advertisement Approved By Admin","Advertisement Approved By Influencer","Advertisement Declined By Admin","Declined By Influencer","Published By Influencer"]

  def self.get_advertisement_count_of_particular_advertiser(advertiser_id)
    count = Advertisement.where(:advertiser_id => advertiser_id).count
    count
  end
 # influencer_id: '1' advertiser_id: '6' category: celebrity advertisement_status: '3' ivars: :@permitted: false
  def self.search(params)
    # raise params.to_yaml
    conditions = []
    conditions << "influencer_id = #{params[:influencer_id]}" if params[:influencer_id].present?
    conditions << "advertiser_id =' #{params[:advertiser_id]}'" if params[:advertiser_id].present?
    conditions << "status = #{params[:advertisement_status]}" if params[:advertisement_status].present?
    condition = conditions.join(' and ')
    self.where(condition)
  end

end

app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
     has_many :advertisements

    scope :most_recent, -> (limit) { order("created_at desc").limit(limit) }

  def self.reset_password
  end

end

app/models/app_configuration.rb
class AppConfiguration < ActiveRecord::Base
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	belongs_to :advertiser
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/influencer.rb
class Influencer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_one :social_account
    has_one :influencer_financial_info

    has_many :advertisements
    scope :most_recent, -> (limit) { order("created_at desc").limit(limit) }
    def online
      if self.last_sign_in_at < 5.minutes.from_now
        true
      else
        false
      end
    end

end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  ACTIVITY_TYPE = {"advertiser_sign_up"=>1,"influencer_sign_up"=>2,"new_ad_creation"=>3,"new_ad_published"=>4}
end

app/models/page_insight.rb
class PageInsight < ActiveRecord::Base
  serialize :page_consumptions_by_consumption_type
end

app/models/pending_notification.rb
class PendingNotification < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/social_account.rb
class SocialAccount < ActiveRecord::Base
  validates_uniqueness_of :facebook_page_id
  # has_one :page_insight, :foreign_key => :facebook_page_id
  def self.search(params)
    # raise params.to_yaml
    conditions = []
    conditions << "platform_type_id = '#{params[:platform_type_id]}'" if params[:platform_type_id].present?
    conditions << "country = '#{params[:country]}'" if params[:country].present?
    conditions << "category = '#{params[:category]}'" if params[:category].present?
    condition = conditions.join(' and ')
    if params[:facebook_page_count].present? and params[:facebook_page_count] == "htol"
      self.where(condition).order('facebook_page_count DESC')
    elsif params[:facebook_page_count].present? and params[:facebook_page_count] == "ltoh"
      self.where(condition).order('facebook_page_count ASC')
    else
      self.where(condition)
    end

  end

  def page_insight
    PageInsight.where(:facebook_page_id=>self.facebook_page_id)
  end

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
 end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_admin!

  def index
    if !current_admin.has_role? :Admin
      flash[:danger] = "You Are Not the Authentic Admin, Contact Admin to get access"
      reset_session
      redirect_to "/unauthorized"
    else
      @earned_today = today_earning
      @monthly_earning = monthly_earning
      @published_ad_count = published_ad_count
      @infleuncer_count = Influencer.count
      @recent_registered_advertisers = Advertiser.most_recent(5)
      @recent_registered_influencers = Influencer.most_recent(5)
    end
  end

end

app/controllers/news_letters_controller.rb
class NewsLettersController < ApplicationController
  def index
    @breadcrumb = {'Dashboard' => root_url, 'Newsletters' => ''}
    @influencers = Influencer.all.order("Id DESC")
    @advertisers = Advertiser.all.order("Id DESC")
    @search = Influencer.new
    params[:user_type] = "advertiser" unless params[:user_type].present? and params[:user_type]!="Select"
    @table_data = eval(params[:user_type].titleize).all
    @table_data = eval(params[:user_type].titleize).where("name like ?","%#{params[:keyword]}%") if params[:keyword].present?
    @table_data = eval(params[:user_type].titleize).where("name like ?","#{params[:alphabet]}%") if params[:alphabet].present?
    @table_data = @table_data.paginate(:page=>params[:page],:per_page=>10)
  end

  def send_newsletters
      subject = params[:subject]
      message = params[:message]
      attachment ||= params[:mail][:attachment] rescue nil
      upload = ""
      if attachment.present?
       upload = Cloudinary::Uploader.upload(attachment,:eager => [{ :width => 600}]) #returns 600px wide image
       attachment_link ||= upload["url"]
      end
      #send to all
      if params[:sent_to_all_influencers] == "on"
        @all_emails = Influencer.pluck(:email)
        @all_emails.each_slice(100) do |email|
          NotificationMailer.delay(run_at: 1.minutes.from_now).send_mail_from_admin(email,subject,message,attachment_link)
        end
      else
        # raise params.to_yaml
        @all_emails = params[:mail_to].split(",")
        @all_emails.each_slice(100) do |email|
              NotificationMailer.delay(run_at: 1.minutes.from_now).send_mail_from_admin(email,subject,message,attachment_link)
          end
      #   if params[:sent_to_all_advertisers] == "off"
      #     @all_emails = Advertiser.pluck(:email)
      #     @all_emails.each_slice(100) do |email|
      #       NotificationMailer.send_mail_from_admin(email,subject,message,attachment_link)
      #   end
      # else
      end
      # end
      redirect_to :back
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/helpers/news_letters_helper.rb
module NewsLettersHelper
end

app/views/news_letters/index.html.erb
<%=render :partial=>"layouts/header"%>
<%=render :partial=>"layouts/left_panel"%>
<section class="main-content-wrapper column">
   <section id="main-content">
        <div class="row">
           <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                   <li><a href="#">Dashboard</a></li>
                   <li class="active">Newsletter</li>
               </ul>
               <!--breadcrumbs end -->
           <h1 class="h1"><i class="fa fa-envelope"></i> Newsletter</h1>
       </div>
       </div>

      <div class="row">
      <div class="col-md-12">
      <div class="borderBox">
      <div class="row">
      <%=form_for :search,:url=>news_letters_path, :method=>"get" do |f|%>

      <div class="col-md-3">
      <div class="form-group">

      <label class="" for="">User Type</label>
      <%=select_tag(:user_type,options_for_select([["Advertiser","advertiser"],["Influencer","influencer"]],params[:user_type]),:class=>"form-control")%>

      </div>
      </div>

      <div class="col-md-3">
      <div class="form-group">
        <label class="" for="">Category</label>
        <%=f.select(:category,options_for_select(Category.pluck(:category_name)),{},:class=>"form-control")%>
        </div>
      </div>

      <div class="col-md-3">
      <div class="form-group">

      <label class="" for="">Type Keyword</label>
        <input type="text" name="keyword" value="<%=params[:keyword]%>" class="form-control">
        </div>
      </div>

      <div class="col-md-3">
        <button type="submit" class="btn btn-primary mgTop30" style="margin-top: 9%">Search</button>
        <a href="/news_letters" class="btn btn-primary mgTop30" style="margin-top: 9%">Clear</a>
      </div>

      <%end%>

      </div>

      <div class="row">
      <div class="col-md-12">
      <div class="pull-left">Search By:</div>
      <div class="btn-toolbar">
      <div class="btn-group btn-group-sm">
      <a href="<%=news_letters_path(alphabet:'a')%>" class="btn btn-default">A</a>
      <a href="<%=news_letters_path(alphabet:'b')%>" class="btn btn-default">B</a>
      <a href="<%=news_letters_path(alphabet:'c')%>" class="btn btn-default">C</a>
      <a href="<%=news_letters_path(alphabet:'d')%>" class="btn btn-default">D</a>
      <a href="<%=news_letters_path(alphabet:'e')%>" class="btn btn-default">E</a>
      <a href="<%=news_letters_path(alphabet:'f')%>" class="btn btn-default">F</a>
      <a href="<%=news_letters_path(alphabet:'g')%>" class="btn btn-default">G</a>
      <a href="<%=news_letters_path(alphabet:'h')%>" class="btn btn-default">H</a>
      <a href="<%=news_letters_path(alphabet:'i')%>" class="btn btn-default">I</a>
      <a href="<%=news_letters_path(alphabet:'j')%>" class="btn btn-default">J</a>
      <a href="<%=news_letters_path(alphabet:'k')%>" class="btn btn-default">K</a>
      <a href="<%=news_letters_path(alphabet:'l')%>" class="btn btn-default">L</a>
      <a href="<%=news_letters_path(alphabet:'m')%>" class="btn btn-default">M</a>
      <a href="<%=news_letters_path(alphabet:'n')%>" class="btn btn-default">N</a>
      <a href="<%=news_letters_path(alphabet:'o')%>" class="btn btn-default">O</a>
      <a href="<%=news_letters_path(alphabet:'p')%>" class="btn btn-default">P</a>
      <a href="<%=news_letters_path(alphabet:'q')%>" class="btn btn-default">Q</a>
      <a href="<%=news_letters_path(alphabet:'r')%>" class="btn btn-default">R</a>
      <a href="<%=news_letters_path(alphabet:'s')%>" class="btn btn-default">S</a>
      <a href="<%=news_letters_path(alphabet:'t')%>" class="btn btn-default">T</a>
      <a href="<%=news_letters_path(alphabet:'u')%>" class="btn btn-default">U</a>
      <a href="<%=news_letters_path(alphabet:'v')%>" class="btn btn-default">V</a>
      <a href="<%=news_letters_path(alphabet:'w')%>" class="btn btn-default">W</a>
      <a href="<%=news_letters_path(alphabet:'x')%>" class="btn btn-default">X</a>
      <a href="<%=news_letters_path(alphabet:'y')%>" class="btn btn-default">Y</a>
      <a href="<%=news_letters_path(alphabet:'z')%>" class="btn btn-default">Z</a>
      </div>
      </div>
      </div>
      </div>
      </div>
      </div>
</div>

<div class="row">
     <div class="col-md-12">
         <div class="panel panel-default">
           <div class="panel-body">
                  <div class="row">
                     <div class="col-md-12">
                       <div class="table-responsive">
                         <table id="display-table" class="table table-striped" cellspacing="0" width="100%">
                         <thead>
                             <tr>
                                 <th>User Type</th>
                                 <%if @table_data.class.to_s.split(":").first == "Influencer" %>
                                  <th>Category</th>
                                 <%end%>
                                 <th>Name</th>
                                 <th>Email</th>
                             </tr>
                         </thead>

                         <tbody>
                           <%@table_data.each do |d|%>
                             <tr>
                                 <td><input type="checkbox" id="ck_user" onclick="add_new_email(this.value)" value="<%=d.email%>"></td>
                                 <td><%=d.class%></td>
                                 <%if @table_data.class.to_s.split(":").first == "Influencer" %>
                                 <td><%=d.category%></td>
                                 <%end%>
                                 <td><%=d.name%></td>
                                 <td><%=d.email%></td>
                             </tr>
                             <%end%>
                         </tbody>
                     </table>
                     </div>
                     </div>
                 </div>

                 <!-- Pagination -->
         <div class="row">
           <div class="col-md-6">
               <div class="dataTables_info" id=""> <%= page_entries_info @table_data%></div>
             </div>
             <div class="col-md-6">
               <%=will_paginate @table_data, :class=>"dataTables_paginate paging_bootstrap pull-right dataTables_info"%>
             </div>
         </div>

             </div>
      </div>
 </div>
</div>

<div class="row">
<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-body">
    <%=form_for "send_newsletters",:url=>send_newsletters_news_letters_path,:method=>"post",:id=>"ddd" do%>
    <header>
    <h2>New Message</h2>
    </header>

    <div class="row">
    <div class="col-md-12">
    <div class="panel view-compose-body">
    <div class="panel-body">

      <div class="form-group">
        <div class="row">
          <div class="col-md-3">
            <label class="checkbox-inline">
            <input class="icheck" type="checkbox" name="sent_to_all_influencers" id="mail_all_influencers" onclick="send_to_all_influencers()">send to all influencers</label>
          </div>
          <div class="col-md-3">
            <label class="checkbox-inline">
            <input class="icheck" type="checkbox" name="sent_to_all_advertisers" id="mail_all_advertisers" onclick="send_to_all_advertisers()">send to all advertisers</label>
          </div>
        </div>
      </div>

    <div class="form-group">
        <%=text_field_tag :mail_to,"",:placeholder=>"Email",:class=>"form-control"%>
    </div>

    <div class="form-group">
      <%=text_field_tag :subject,"",:placeholder=>"Subject",:class=>"form-control"%>
    </div>

    <%=text_area_tag :message,"",:row=>"5",:cols=>"40",:placeholder=>"Enter message",:style=>"width:100%;height:200px",:class=>"textarea form-control"%>

    </div>
    <div class="panel-body"><%=file_field_tag :attachment, :class=>"btn btn-default btn-sm pull-right"  %></div>

    <div class="panel-footer">
      <%=submit_tag "Send", :class=>"btn btn-sm btn-primary"%>
      <button class="btn btn-default btn-sm "><i class="fa fa-times"></i> Discard</button>
    </div>
    </div>
    </div>
    </div>
    <%end%>
    </div>
  </div>
</div>
</div>

<script>
function send_to_all_influencers(){
  if ($("#mail_all_influencers").is(":checked") == true) {
        // $("input[type=checkbox]").prop("checked","checked");
        $("#mail_to").attr("readonly",true);
    }
    else {
        $("input[type=checkbox]").prop("checked",false);
        $("#mail_to").attr("readonly",false);
    }}
    function send_to_all_advertisers(){
      if ($("#mail_all_advertisers").is(":checked") == true) {
            // $("input[type=checkbox]").prop("checked","checked");
            $("#mail_to").attr("readonly",true);
        }
        else {
            // $("input[type=checkbox]").prop("checked",false);
            $("#mail_to").attr("readonly",false);
        }}

    function add_new_email(email) {
      console.log(email);
      $("#mail_to").val($("#mail_to").val()+email+",");
    }
    $($("form")[1]).attr("ectype","multipart/form-data")
</script>

   </section>
</section>